/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */


package search;

/**
 * In this enum we collect all the fieldnames we allow as queries. There should be some documentation provided
 * @author Arne Stabenau
 *
 */
public enum Fields {
	anywhere, // when you look for anything, not part of an answer, any source interprets this differently
	resourceType, // the WITH resource type 
	// for the within search, this might be useful
	administrative_isPublic,
	administrative_access_READ, // userids are in here
	administrative_access_WRITE,
	administrative_access_OWN,
	
	administrative_created, // date when this record was created
	administrative_lastModified, //
	administrative_externalId, // usually the id in the last provenance entry
	administrative_withURI, //
	
	// the collections this is in
	collectedIn,
	
	collectedBy_READ, // which users have this record  
	collectedBy_WRITE, // TODO: Clarify if the access level is needed here   
	collectedBy_OWN, //  
	
	// provenance info
	provenance_provider,
	provenance_uri,
	provenance_resourceId,
	
	// dataprovider, source 
	provenance_dataprovider, // an extra field for the first provider in the provenance chain
	provenance_source, // the last provider in the provenance chain
	
	// there is potentially more than one media in the resource, so the search will be not accurate if you combine 
	// attributes together (like withRights and quality .. can't search for free and high quality <b> records <b>
	// a separate media index obviously can do that
	media_type,
	media_withRights,
	media_quality, // needs some nice enum values
	media_mimeType,
	
	//
	// descriptive data fields
	//
	
	descriptiveData_dcidentifier, // supports language, without language, searches everything and the uri
	descriptiveData_dcidentifier_uri, // can be uri, 
	
	descriptiveData_dclanguage, // supports language (free text language value in different languages
	descriptiveData_dclanguage_uri,
	
	descriptiveData_dctype,
	descriptiveData_dctype_uri,
	
	descriptiveData_label,
	
	descriptiveData_dcformat,
	descriptiveData_dccreated,
	
	descriptiveData_isShownBy,
	descriptiveData_isShownAt,
	
	descriptiveData_rdfType, // this is mostly useful as exact match query
	
	
}
/*
_all
_all_VRT
_all_VRT.all
_all_af
_all_af.all
_all_an
_all_an.all
_all_ar
_all_ar.all
_all_ast
_all_ast.all
_all_be
_all_be.all
_all_bg
_all_bg.all
_all_bn
_all_bn.all
_all_br
_all_br.all
_all_ca
_all_ca.all
_all_cs
_all_cs.all
_all_cy
_all_cy.all
_all_da
_all_da.all
_all_de
_all_de.all
_all_def
_all_def.all
_all_default
_all_default.all
_all_el
_all_el.all
_all_en
_all_en.all
_all_es
_all_es.all
_all_et
_all_et.all
_all_eu
_all_eu.all
_all_fi
_all_fi.all
_all_fr
_all_fr.all
_all_gaa
_all_gaa.all
_all_gl
_all_gl.all
_all_gu
_all_gu.all
_all_he
_all_he.all
_all_hr
_all_hr.all
_all_ht
_all_ht.all
_all_hu
_all_hu.all
_all_id
_all_id.all
_all_is
_all_is.all
_all_it
_all_it.all
_all_ja
_all_ja.all
_all_ko
_all_ko.all
_all_la
_all_la.all
_all_lt
_all_lt.all
_all_lv
_all_lv.all
_all_mk
_all_mk.all
_all_ml
_all_ml.all
_all_mr
_all_mr.all
_all_ms
_all_ms.all
_all_mt
_all_mt.all
_all_nb
_all_nb.all
_all_nl
_all_nl.all
_all_no
_all_no.all
_all_oc
_all_oc.all
_all_pl
_all_pl.all
_all_pt
_all_pt.all
_all_ro
_all_ro.all
_all_ru
_all_ru.all
_all_sk
_all_sk.all
_all_sl
_all_sl.all
_all_so
_all_so.all
_all_sq
_all_sq.all
_all_sr
_all_sr.all
_all_sv
_all_sv.all
_all_sw
_all_sw.all
_all_ta
_all_ta.all
_all_te
_all_te.all
_all_th
_all_th.all
_all_tl
_all_tl.all
_all_tr
_all_tr.all
_all_uk
_all_uk.all
_all_uri
_all_uri.all
_all_vi
_all_vi.all
_all_yi
_all_yi.all
_all_zxx
_all_zxx.all

_source
_type
_uid
_version

altLabels
altLabels.VRT
altLabels.VRT.all
altLabels.af
altLabels.af.all
altLabels.an
altLabels.an.all
altLabels.ast
altLabels.ast.all
altLabels.bg
altLabels.bg.all
altLabels.br
altLabels.br.all
altLabels.ca
altLabels.ca.all
altLabels.cs
altLabels.cs.all
altLabels.cy
altLabels.cy.all
altLabels.da
altLabels.da.all
altLabels.de
altLabels.de.all
altLabels.def
altLabels.def.all
altLabels.default
altLabels.default.all
altLabels.el
altLabels.el.all
altLabels.en
altLabels.en.all
altLabels.es
altLabels.es.all
altLabels.et
altLabels.et.all
altLabels.eu
altLabels.eu.all
altLabels.fi
altLabels.fi.all
altLabels.fr
altLabels.fr.all
altLabels.gaa
altLabels.gaa.all
altLabels.gl
altLabels.gl.all
altLabels.hr
altLabels.hr.all
altLabels.ht
altLabels.ht.all
altLabels.hu
altLabels.hu.all
altLabels.id
altLabels.id.all
altLabels.is
altLabels.is.all
altLabels.it
altLabels.it.all
altLabels.la
altLabels.la.all
altLabels.lt
altLabels.lt.all
altLabels.lv
altLabels.lv.all
altLabels.ms
altLabels.ms.all
altLabels.mt
altLabels.mt.all
altLabels.nl
altLabels.nl.all
altLabels.no
altLabels.no.all
altLabels.oc
altLabels.oc.all
altLabels.pl
altLabels.pl.all
altLabels.pt
altLabels.pt.all
altLabels.ro
altLabels.ro.all
altLabels.ru
altLabels.ru.all
altLabels.sk
altLabels.sk.all
altLabels.sl
altLabels.sl.all
altLabels.so
altLabels.so.all
altLabels.sq
altLabels.sq.all
altLabels.sv
altLabels.sv.all
altLabels.sw
altLabels.sw.all
altLabels.tl
altLabels.tl.all
altLabels.tr
altLabels.tr.all
altLabels.unknown
altLabels.unknown.all
altLabels_all
altLabels_all.all

collectedId
collectedId.all

creatorUsername
creatorUsername.all

credits
credits.all

dataProvider
dataProvider.all

dates
dccontributor
dccontributor.af
dccontributor.af.all
dccontributor.an
dccontributor.an.all
dccontributor.ast
dccontributor.ast.all
dccontributor.br
dccontributor.br.all
dccontributor.ca
dccontributor.ca.all
dccontributor.cs
dccontributor.cs.all
dccontributor.cy
dccontributor.cy.all
dccontributor.da
dccontributor.da.all
dccontributor.de
dccontributor.de.all
dccontributor.default
dccontributor.default.all
dccontributor.el
dccontributor.el.all
dccontributor.en
dccontributor.en.all
dccontributor.es
dccontributor.es.all
dccontributor.et
dccontributor.et.all
dccontributor.eu
dccontributor.eu.all
dccontributor.fi
dccontributor.fi.all
dccontributor.fr
dccontributor.fr.all
dccontributor.gaa
dccontributor.gaa.all
dccontributor.gl
dccontributor.gl.all
dccontributor.hr
dccontributor.hr.all
dccontributor.ht
dccontributor.ht.all
dccontributor.hu
dccontributor.hu.all
dccontributor.id
dccontributor.id.all
dccontributor.is
dccontributor.is.all
dccontributor.it
dccontributor.it.all
dccontributor.lt
dccontributor.lt.all
dccontributor.lv
dccontributor.lv.all
dccontributor.ms
dccontributor.ms.all
dccontributor.mt
dccontributor.mt.all
dccontributor.nl
dccontributor.nl.all
dccontributor.no
dccontributor.no.all
dccontributor.oc
dccontributor.oc.all
dccontributor.pl
dccontributor.pl.all
dccontributor.pt
dccontributor.pt.all
dccontributor.ro
dccontributor.ro.all
dccontributor.ru
dccontributor.ru.all
dccontributor.sk
dccontributor.sk.all
dccontributor.sl
dccontributor.sl.all
dccontributor.so
dccontributor.so.all
dccontributor.sq
dccontributor.sq.all
dccontributor.sv
dccontributor.sv.all
dccontributor.sw
dccontributor.sw.all
dccontributor.tl
dccontributor.tl.all
dccontributor.tr
dccontributor.tr.all
dccontributor.unknown
dccontributor.unknown.all
dccontributor.uri
dccontributor.uri.all
dccontributor.vi
dccontributor.vi.all

dccoverage
dccoverage.af
dccoverage.af.all
dccoverage.an
dccoverage.an.all
dccoverage.be
dccoverage.be.all
dccoverage.bg
dccoverage.bg.all
dccoverage.br
dccoverage.br.all
dccoverage.ca
dccoverage.ca.all
dccoverage.cs
dccoverage.cs.all
dccoverage.cy
dccoverage.cy.all
dccoverage.da
dccoverage.da.all
dccoverage.de
dccoverage.de.all
dccoverage.default
dccoverage.default.all
dccoverage.el
dccoverage.el.all
dccoverage.en
dccoverage.en.all
dccoverage.es
dccoverage.es.all
dccoverage.et
dccoverage.et.all
dccoverage.eu
dccoverage.eu.all
dccoverage.fi
dccoverage.fi.all
dccoverage.fr
dccoverage.fr.all
dccoverage.gaa
dccoverage.gaa.all
dccoverage.gl
dccoverage.gl.all
dccoverage.hu
dccoverage.hu.all
dccoverage.is
dccoverage.is.all
dccoverage.it
dccoverage.it.all
dccoverage.lt
dccoverage.lt.all
dccoverage.lv
dccoverage.lv.all
dccoverage.ms
dccoverage.ms.all
dccoverage.mt
dccoverage.mt.all
dccoverage.nl
dccoverage.nl.all
dccoverage.no
dccoverage.no.all
dccoverage.oc
dccoverage.oc.all
dccoverage.pl
dccoverage.pl.all
dccoverage.pt
dccoverage.pt.all
dccoverage.ro
dccoverage.ro.all
dccoverage.sk
dccoverage.sk.all
dccoverage.sl
dccoverage.sl.all
dccoverage.so
dccoverage.so.all
dccoverage.sv
dccoverage.sv.all
dccoverage.sw
dccoverage.sw.all
dccoverage.tl
dccoverage.tl.all
dccoverage.tr
dccoverage.tr.all
dccoverage.uk
dccoverage.uk.all
dccoverage.unknown
dccoverage.unknown.all
dccoverage.uri
dccoverage.uri.all
dccoverage.vi
dccoverage.vi.all
dccreated
dccreator
dccreator.af
dccreator.af.all
dccreator.an
dccreator.an.all
dccreator.ast
dccreator.ast.all
dccreator.be
dccreator.be.all
dccreator.bg
dccreator.bg.all
dccreator.br
dccreator.br.all
dccreator.ca
dccreator.ca.all
dccreator.cs
dccreator.cs.all
dccreator.cy
dccreator.cy.all
dccreator.da
dccreator.da.all
dccreator.de
dccreator.de.all
dccreator.default
dccreator.default.all
dccreator.el
dccreator.el.all
dccreator.en
dccreator.en.all
dccreator.es
dccreator.es.all
dccreator.et
dccreator.et.all
dccreator.eu
dccreator.eu.all
dccreator.fi
dccreator.fi.all
dccreator.fr
dccreator.fr.all
dccreator.gaa
dccreator.gaa.all
dccreator.gl
dccreator.gl.all
dccreator.hr
dccreator.hr.all
dccreator.ht
dccreator.ht.all
dccreator.hu
dccreator.hu.all
dccreator.id
dccreator.id.all
dccreator.is
dccreator.is.all
dccreator.it
dccreator.it.all
dccreator.la
dccreator.la.all
dccreator.lt
dccreator.lt.all
dccreator.lv
dccreator.lv.all
dccreator.mk
dccreator.mk.all
dccreator.ms
dccreator.ms.all
dccreator.mt
dccreator.mt.all
dccreator.nl
dccreator.nl.all
dccreator.no
dccreator.no.all
dccreator.oc
dccreator.oc.all
dccreator.pl
dccreator.pl.all
dccreator.pt
dccreator.pt.all
dccreator.ro
dccreator.ro.all
dccreator.ru
dccreator.ru.all
dccreator.sk
dccreator.sk.all
dccreator.sl
dccreator.sl.all
dccreator.so
dccreator.so.all
dccreator.sq
dccreator.sq.all
dccreator.sr
dccreator.sr.all
dccreator.sv
dccreator.sv.all
dccreator.sw
dccreator.sw.all
dccreator.tl
dccreator.tl.all
dccreator.tr
dccreator.tr.all
dccreator.uk
dccreator.uk.all
dccreator.und
dccreator.und.all
dccreator.unknown
dccreator.unknown.all
dccreator.uri
dccreator.uri.all
dccreator.vi
dccreator.vi.all
dccreator.zxx
dccreator.zxx.all
dcformat
dcformat.af
dcformat.af.all
dcformat.an
dcformat.an.all
dcformat.br
dcformat.br.all
dcformat.ca
dcformat.ca.all
dcformat.cs
dcformat.cs.all
dcformat.cy
dcformat.cy.all
dcformat.da
dcformat.da.all
dcformat.de
dcformat.de.all
dcformat.default
dcformat.default.all
dcformat.el
dcformat.el.all
dcformat.en
dcformat.en.all
dcformat.es
dcformat.es.all
dcformat.et
dcformat.et.all
dcformat.eu
dcformat.eu.all
dcformat.fi
dcformat.fi.all
dcformat.fr
dcformat.fr.all
dcformat.gaa
dcformat.gaa.all
dcformat.gl
dcformat.gl.all
dcformat.he
dcformat.he.all
dcformat.hr
dcformat.hr.all
dcformat.ht
dcformat.ht.all
dcformat.hu
dcformat.hu.all
dcformat.is
dcformat.is.all
dcformat.it
dcformat.it.all
dcformat.lt
dcformat.lt.all
dcformat.mt
dcformat.mt.all
dcformat.nl
dcformat.nl.all
dcformat.no
dcformat.no.all
dcformat.oc
dcformat.oc.all
dcformat.pl
dcformat.pl.all
dcformat.pt
dcformat.pt.all
dcformat.ro
dcformat.ro.all
dcformat.sk
dcformat.sk.all
dcformat.so
dcformat.so.all
dcformat.sv
dcformat.sv.all
dcformat.tl
dcformat.tl.all
dcformat.tr
dcformat.tr.all
dcformat.unknown
dcformat.unknown.all
dcformat.uri
dcformat.uri.all
dcformat.zxx
dcformat.zxx.all
dcidentifier
dcidentifier.af
dcidentifier.af.all
dcidentifier.an
dcidentifier.an.all
dcidentifier.ast
dcidentifier.ast.all
dcidentifier.br
dcidentifier.br.all
dcidentifier.ca
dcidentifier.ca.all
dcidentifier.cs
dcidentifier.cs.all
dcidentifier.cy
dcidentifier.cy.all
dcidentifier.da
dcidentifier.da.all
dcidentifier.de
dcidentifier.de.all
dcidentifier.default
dcidentifier.default.all
dcidentifier.el
dcidentifier.el.all
dcidentifier.en
dcidentifier.en.all
dcidentifier.et
dcidentifier.et.all
dcidentifier.eu
dcidentifier.eu.all
dcidentifier.fi
dcidentifier.fi.all
dcidentifier.fr
dcidentifier.fr.all
dcidentifier.gaa
dcidentifier.gaa.all
dcidentifier.gl
dcidentifier.gl.all
dcidentifier.hr
dcidentifier.hr.all
dcidentifier.ht
dcidentifier.ht.all
dcidentifier.hu
dcidentifier.hu.all
dcidentifier.is
dcidentifier.is.all
dcidentifier.it
dcidentifier.it.all
dcidentifier.la
dcidentifier.la.all
dcidentifier.lt
dcidentifier.lt.all
dcidentifier.lv
dcidentifier.lv.all
dcidentifier.ms
dcidentifier.ms.all
dcidentifier.mt
dcidentifier.mt.all
dcidentifier.nl
dcidentifier.nl.all
dcidentifier.no
dcidentifier.no.all
dcidentifier.oc
dcidentifier.oc.all
dcidentifier.pl
dcidentifier.pl.all
dcidentifier.pt
dcidentifier.pt.all
dcidentifier.ro
dcidentifier.ro.all
dcidentifier.sl
dcidentifier.sl.all
dcidentifier.so
dcidentifier.so.all
dcidentifier.sv
dcidentifier.sv.all
dcidentifier.sw
dcidentifier.sw.all
dcidentifier.tl
dcidentifier.tl.all
dcidentifier.unknown
dcidentifier.unknown.all
dcidentifier.uri
dcidentifier.uri.all
dcidentifier.zxx
dcidentifier.zxx.all
dclanguage
dclanguage.def
dclanguage.def.all
dclanguage.default
dclanguage.default.all
dclanguage.en
dclanguage.en.all
dclanguage.unknown
dclanguage.unknown.all
dcrights
dcrights.af
dcrights.af.all
dcrights.an
dcrights.an.all
dcrights.bg
dcrights.bg.all
dcrights.ca
dcrights.ca.all
dcrights.cs
dcrights.cs.all
dcrights.cy
dcrights.cy.all
dcrights.da
dcrights.da.all
dcrights.de
dcrights.de.all
dcrights.default
dcrights.default.all
dcrights.el
dcrights.el.all
dcrights.en
dcrights.en.all
dcrights.es
dcrights.es.all
dcrights.et
dcrights.et.all
dcrights.eu
dcrights.eu.all
dcrights.fr
dcrights.fr.all
dcrights.gaa
dcrights.gaa.all
dcrights.gl
dcrights.gl.all
dcrights.ht
dcrights.ht.all
dcrights.hu
dcrights.hu.all
dcrights.it
dcrights.it.all
dcrights.lt
dcrights.lt.all
dcrights.mk
dcrights.mk.all
dcrights.nl
dcrights.nl.all
dcrights.oc
dcrights.oc.all
dcrights.pl
dcrights.pl.all
dcrights.pt
dcrights.pt.all
dcrights.ro
dcrights.ro.all
dcrights.sk
dcrights.sk.all
dcrights.sl
dcrights.sl.all
dcrights.so
dcrights.so.all
dcrights.sv
dcrights.sv.all
dcrights.unknown
dcrights.unknown.all
dcrights.uri
dcrights.uri.all
dctermsmedium
dctermsmedium.af
dctermsmedium.af.all
dctermsmedium.bg
dctermsmedium.bg.all
dctermsmedium.br
dctermsmedium.br.all
dctermsmedium.ca
dctermsmedium.ca.all
dctermsmedium.cs
dctermsmedium.cs.all
dctermsmedium.cy
dctermsmedium.cy.all
dctermsmedium.da
dctermsmedium.da.all
dctermsmedium.de
dctermsmedium.de.all
dctermsmedium.default
dctermsmedium.default.all
dctermsmedium.el
dctermsmedium.el.all
dctermsmedium.en
dctermsmedium.en.all
dctermsmedium.et
dctermsmedium.et.all
dctermsmedium.eu
dctermsmedium.eu.all
dctermsmedium.fi
dctermsmedium.fi.all
dctermsmedium.fr
dctermsmedium.fr.all
dctermsmedium.gaa
dctermsmedium.gaa.all
dctermsmedium.gl
dctermsmedium.gl.all
dctermsmedium.hr
dctermsmedium.hr.all
dctermsmedium.hu
dctermsmedium.hu.all
dctermsmedium.it
dctermsmedium.it.all
dctermsmedium.lt
dctermsmedium.lt.all
dctermsmedium.mt
dctermsmedium.mt.all
dctermsmedium.nl
dctermsmedium.nl.all
dctermsmedium.no
dctermsmedium.no.all
dctermsmedium.pl
dctermsmedium.pl.all
dctermsmedium.pt
dctermsmedium.pt.all
dctermsmedium.ro
dctermsmedium.ro.all
dctermsmedium.sk
dctermsmedium.sk.all
dctermsmedium.sl
dctermsmedium.sl.all
dctermsmedium.sv
dctermsmedium.sv.all
dctermsmedium.tl
dctermsmedium.tl.all
dctermsmedium.unknown
dctermsmedium.unknown.all
dctermsmedium.uri
dctermsmedium.uri.all
dctermsspatial
dctermsspatial.aa
dctermsspatial.aa.all
dctermsspatial.ab
dctermsspatial.ab.all
dctermsspatial.af
dctermsspatial.af.all
dctermsspatial.ak
dctermsspatial.ak.all
dctermsspatial.am
dctermsspatial.am.all
dctermsspatial.an
dctermsspatial.an.all
dctermsspatial.ar
dctermsspatial.ar.all
dctermsspatial.as
dctermsspatial.as.all
dctermsspatial.ast
dctermsspatial.ast.all
dctermsspatial.av
dctermsspatial.av.all
dctermsspatial.ay
dctermsspatial.ay.all
dctermsspatial.az
dctermsspatial.az.all
dctermsspatial.be
dctermsspatial.be.all
dctermsspatial.bg
dctermsspatial.bg.all
dctermsspatial.bh
dctermsspatial.bh.all
dctermsspatial.bi
dctermsspatial.bi.all
dctermsspatial.bm
dctermsspatial.bm.all
dctermsspatial.bn
dctermsspatial.bn.all
dctermsspatial.bo
dctermsspatial.bo.all
dctermsspatial.br
dctermsspatial.br.all
dctermsspatial.bs
dctermsspatial.bs.all
dctermsspatial.ca
dctermsspatial.ca.all
dctermsspatial.ce
dctermsspatial.ce.all
dctermsspatial.ch
dctermsspatial.ch.all
dctermsspatial.co
dctermsspatial.co.all
dctermsspatial.cs
dctermsspatial.cs.all
dctermsspatial.cu
dctermsspatial.cu.all
dctermsspatial.cv
dctermsspatial.cv.all
dctermsspatial.cy
dctermsspatial.cy.all
dctermsspatial.da
dctermsspatial.da.all
dctermsspatial.de
dctermsspatial.de.all
dctermsspatial.default
dctermsspatial.default.all
dctermsspatial.dv
dctermsspatial.dv.all
dctermsspatial.dz
dctermsspatial.dz.all
dctermsspatial.ee
dctermsspatial.ee.all
dctermsspatial.el
dctermsspatial.el.all
dctermsspatial.en
dctermsspatial.en.all
dctermsspatial.eo
dctermsspatial.eo.all
dctermsspatial.es
dctermsspatial.es.all
dctermsspatial.et
dctermsspatial.et.all
dctermsspatial.eu
dctermsspatial.eu.all
dctermsspatial.fa
dctermsspatial.fa.all
dctermsspatial.ff
dctermsspatial.ff.all
dctermsspatial.fi
dctermsspatial.fi.all
dctermsspatial.fj
dctermsspatial.fj.all
dctermsspatial.fo
dctermsspatial.fo.all
dctermsspatial.fr
dctermsspatial.fr.all
dctermsspatial.fy
dctermsspatial.fy.all
dctermsspatial.gaa
dctermsspatial.gaa.all
dctermsspatial.gd
dctermsspatial.gd.all
dctermsspatial.gl
dctermsspatial.gl.all
dctermsspatial.gn
dctermsspatial.gn.all
dctermsspatial.gu
dctermsspatial.gu.all
dctermsspatial.gv
dctermsspatial.gv.all
dctermsspatial.ha
dctermsspatial.ha.all
dctermsspatial.he
dctermsspatial.he.all
dctermsspatial.hi
dctermsspatial.hi.all
dctermsspatial.hr
dctermsspatial.hr.all
dctermsspatial.ht
dctermsspatial.ht.all
dctermsspatial.hu
dctermsspatial.hu.all
dctermsspatial.hy
dctermsspatial.hy.all
dctermsspatial.ia
dctermsspatial.ia.all
dctermsspatial.id
dctermsspatial.id.all
dctermsspatial.ie
dctermsspatial.ie.all
dctermsspatial.ig
dctermsspatial.ig.all
dctermsspatial.ii
dctermsspatial.ii.all
dctermsspatial.io
dctermsspatial.io.all
dctermsspatial.is
dctermsspatial.is.all
dctermsspatial.it
dctermsspatial.it.all
dctermsspatial.ja
dctermsspatial.ja.all
dctermsspatial.jv
dctermsspatial.jv.all
dctermsspatial.ka
dctermsspatial.ka.all
dctermsspatial.kg
dctermsspatial.kg.all
dctermsspatial.ki
dctermsspatial.ki.all
dctermsspatial.kj
dctermsspatial.kj.all
dctermsspatial.kk
dctermsspatial.kk.all
dctermsspatial.kl
dctermsspatial.kl.all
dctermsspatial.km
dctermsspatial.km.all
dctermsspatial.kn
dctermsspatial.kn.all
dctermsspatial.ko
dctermsspatial.ko.all
dctermsspatial.ks
dctermsspatial.ks.all
dctermsspatial.ku
dctermsspatial.ku.all
dctermsspatial.kw
dctermsspatial.kw.all
dctermsspatial.ky
dctermsspatial.ky.all
dctermsspatial.la
dctermsspatial.la.all
dctermsspatial.lb
dctermsspatial.lb.all
dctermsspatial.lg
dctermsspatial.lg.all
dctermsspatial.li
dctermsspatial.li.all
dctermsspatial.ln
dctermsspatial.ln.all
dctermsspatial.lo
dctermsspatial.lo.all
dctermsspatial.lt
dctermsspatial.lt.all
dctermsspatial.lu
dctermsspatial.lu.all
dctermsspatial.lv
dctermsspatial.lv.all
dctermsspatial.mg
dctermsspatial.mg.all
dctermsspatial.mh
dctermsspatial.mh.all
dctermsspatial.mi
dctermsspatial.mi.all
dctermsspatial.mk
dctermsspatial.mk.all
dctermsspatial.ml
dctermsspatial.ml.all
dctermsspatial.mn
dctermsspatial.mn.all
dctermsspatial.mo
dctermsspatial.mo.all
dctermsspatial.mr
dctermsspatial.mr.all
dctermsspatial.ms
dctermsspatial.ms.all
dctermsspatial.mt
dctermsspatial.mt.all
dctermsspatial.my
dctermsspatial.my.all
dctermsspatial.na
dctermsspatial.na.all
dctermsspatial.nb
dctermsspatial.nb.all
dctermsspatial.nd
dctermsspatial.nd.all
dctermsspatial.nds
dctermsspatial.nds.all
dctermsspatial.ne
dctermsspatial.ne.all
dctermsspatial.ng
dctermsspatial.ng.all
dctermsspatial.nl
dctermsspatial.nl.all
dctermsspatial.nn
dctermsspatial.nn.all
dctermsspatial.no
dctermsspatial.no.all
dctermsspatial.ny
dctermsspatial.ny.all
dctermsspatial.oc
dctermsspatial.oc.all
dctermsspatial.om
dctermsspatial.om.all
dctermsspatial.or
dctermsspatial.or.all
dctermsspatial.os
dctermsspatial.os.all
dctermsspatial.pa
dctermsspatial.pa.all
dctermsspatial.pi
dctermsspatial.pi.all
dctermsspatial.pl
dctermsspatial.pl.all
dctermsspatial.ps
dctermsspatial.ps.all
dctermsspatial.pt
dctermsspatial.pt.all
dctermsspatial.qu
dctermsspatial.qu.all
dctermsspatial.rm
dctermsspatial.rm.all
dctermsspatial.rn
dctermsspatial.rn.all
dctermsspatial.ro
dctermsspatial.ro.all
dctermsspatial.ru
dctermsspatial.ru.all
dctermsspatial.rw
dctermsspatial.rw.all
dctermsspatial.sa
dctermsspatial.sa.all
dctermsspatial.sc
dctermsspatial.sc.all
dctermsspatial.se
dctermsspatial.se.all
dctermsspatial.sg
dctermsspatial.sg.all
dctermsspatial.sh
dctermsspatial.sh.all
dctermsspatial.si
dctermsspatial.si.all
dctermsspatial.sk
dctermsspatial.sk.all
dctermsspatial.sl
dctermsspatial.sl.all
dctermsspatial.sm
dctermsspatial.sm.all
dctermsspatial.sn
dctermsspatial.sn.all
dctermsspatial.so
dctermsspatial.so.all
dctermsspatial.sq
dctermsspatial.sq.all
dctermsspatial.sr
dctermsspatial.sr.all
dctermsspatial.ss
dctermsspatial.ss.all
dctermsspatial.st
dctermsspatial.st.all
dctermsspatial.su
dctermsspatial.su.all
dctermsspatial.sv
dctermsspatial.sv.all
dctermsspatial.sw
dctermsspatial.sw.all
dctermsspatial.ta
dctermsspatial.ta.all
dctermsspatial.te
dctermsspatial.te.all
dctermsspatial.tg
dctermsspatial.tg.all
dctermsspatial.th
dctermsspatial.th.all
dctermsspatial.ti
dctermsspatial.ti.all
dctermsspatial.tk
dctermsspatial.tk.all
dctermsspatial.tl
dctermsspatial.tl.all
dctermsspatial.tn
dctermsspatial.tn.all
dctermsspatial.to
dctermsspatial.to.all
dctermsspatial.tr
dctermsspatial.tr.all
dctermsspatial.ts
dctermsspatial.ts.all
dctermsspatial.tt
dctermsspatial.tt.all
dctermsspatial.tw
dctermsspatial.tw.all
dctermsspatial.ty
dctermsspatial.ty.all
dctermsspatial.ug
dctermsspatial.ug.all
dctermsspatial.uk
dctermsspatial.uk.all
dctermsspatial.unknown
dctermsspatial.unknown.all
dctermsspatial.ur
dctermsspatial.ur.all
dctermsspatial.uri
dctermsspatial.uri.all
dctermsspatial.uz
dctermsspatial.uz.all
dctermsspatial.ve
dctermsspatial.ve.all
dctermsspatial.vi
dctermsspatial.vi.all
dctermsspatial.vo
dctermsspatial.vo.all
dctermsspatial.wa
dctermsspatial.wa.all
dctermsspatial.wo
dctermsspatial.wo.all
dctermsspatial.xh
dctermsspatial.xh.all
dctermsspatial.yi
dctermsspatial.yi.all
dctermsspatial.yo
dctermsspatial.yo.all
dctermsspatial.zh
dctermsspatial.zh.all
dctermsspatial.zu
dctermsspatial.zu.all
dctermsspatial.zxx
dctermsspatial.zxx.all
dctype
dctype.af
dctype.af.all
dctype.an
dctype.an.all
dctype.bg
dctype.bg.all
dctype.br
dctype.br.all
dctype.ca
dctype.ca.all
dctype.cs
dctype.cs.all
dctype.cy
dctype.cy.all
dctype.da
dctype.da.all
dctype.de
dctype.de.all
dctype.default
dctype.default.all
dctype.el
dctype.el.all
dctype.en
dctype.en.all
dctype.es
dctype.es.all
dctype.et
dctype.et.all
dctype.eu
dctype.eu.all
dctype.fi
dctype.fi.all
dctype.fr
dctype.fr.all
dctype.gaa
dctype.gaa.all
dctype.hr
dctype.hr.all
dctype.ht
dctype.ht.all
dctype.hu
dctype.hu.all
dctype.is
dctype.is.all
dctype.it
dctype.it.all
dctype.lt
dctype.lt.all
dctype.lv
dctype.lv.all
dctype.ms
dctype.ms.all
dctype.mt
dctype.mt.all
dctype.nl
dctype.nl.all
dctype.no
dctype.no.all
dctype.pl
dctype.pl.all
dctype.pt
dctype.pt.all
dctype.ro
dctype.ro.all
dctype.sk
dctype.sk.all
dctype.sl
dctype.sl.all
dctype.so
dctype.so.all
dctype.sq
dctype.sq.all
dctype.sv
dctype.sv.all
dctype.sw
dctype.sw.all
dctype.tl
dctype.tl.all
dctype.uk
dctype.uk.all
dctype.unknown
dctype.unknown.all
dctype.uri
dctype.uri.all
dctype.yi
dctype.yi.all
dctype.zxx
dctype.zxx.all
description
description.VRT
description.VRT.all
description.af
description.af.all
description.an
description.an.all
description.ar
description.ar.all
description.ast
description.ast.all
description.bg
description.bg.all
description.br
description.br.all
description.ca
description.ca.all
description.cs
description.cs.all
description.cy
description.cy.all
description.da
description.da.all
description.de
description.de.all
description.def
description.def.all
description.default
description.default.all
description.el
description.el.all
description.en
description.en.all
description.es
description.es.all
description.et
description.et.all
description.eu
description.eu.all
description.fi
description.fi.all
description.fr
description.fr.all
description.gaa
description.gaa.all
description.gl
description.gl.all
description.he
description.he.all
description.hr
description.hr.all
description.ht
description.ht.all
description.hu
description.hu.all
description.id
description.id.all
description.is
description.is.all
description.it
description.it.all
description.la
description.la.all
description.lt
description.lt.all
description.lv
description.lv.all
description.ms
description.ms.all
description.mt
description.mt.all
description.nl
description.nl.all
description.no
description.no.all
description.oc
description.oc.all
description.pl
description.pl.all
description.pt
description.pt.all
description.ro
description.ro.all
description.ru
description.ru.all
description.sk
description.sk.all
description.sl
description.sl.all
description.so
description.so.all
description.sq
description.sq.all
description.sr
description.sr.all
description.sv
description.sv.all
description.sw
description.sw.all
description.tl
description.tl.all
description.tr
description.tr.all
description.uk
description.uk.all
description.unknown
description.unknown.all
description.vi
description.vi.all
description.zxx
description_all
description_all.all
isPublic
isRelatedTo
isRelatedTo.default
isRelatedTo.default.all
isRelatedTo.en
isRelatedTo.en.all
isRelatedTo.unknown
isRelatedTo.unknown.all
isRelatedTo.uri
isRelatedTo.uri.all
isShownAt
isShownAt.default
isShownAt.default.all
isShownAt.el
isShownAt.el.all
isShownAt.en
isShownAt.en.all
isShownAt.unknown
isShownAt.unknown.all
isShownAt.uri
isShownAt.uri.all
keywords
keywords.af
keywords.af.all
keywords.an
keywords.an.all
keywords.ar
keywords.ar.all
keywords.ast
keywords.ast.all
keywords.be
keywords.be.all
keywords.bg
keywords.bg.all
keywords.bn
keywords.bn.all
keywords.br
keywords.br.all
keywords.ca
keywords.ca.all
keywords.cs
keywords.cs.all
keywords.cy
keywords.cy.all
keywords.da
keywords.da.all
keywords.de
keywords.de.all
keywords.default
keywords.default.all
keywords.el
keywords.el.all
keywords.en
keywords.en.all
keywords.es
keywords.es.all
keywords.et
keywords.et.all
keywords.eu
keywords.eu.all
keywords.fi
keywords.fi.all
keywords.fr
keywords.fr.all
keywords.gaa
keywords.gaa.all
keywords.gl
keywords.gl.all
keywords.gu
keywords.gu.all
keywords.he
keywords.he.all
keywords.hr
keywords.hr.all
keywords.ht
keywords.ht.all
keywords.hu
keywords.hu.all
keywords.id
keywords.id.all
keywords.is
keywords.is.all
keywords.it
keywords.it.all
keywords.ja
keywords.ja.all
keywords.ko
keywords.ko.all
keywords.la
keywords.la.all
keywords.lt
keywords.lt.all
keywords.lv
keywords.lv.all
keywords.ml
keywords.ml.all
keywords.mr
keywords.mr.all
keywords.ms
keywords.ms.all
keywords.mt
keywords.mt.all
keywords.nl
keywords.nl.all
keywords.no
keywords.no.all
keywords.oc
keywords.oc.all
keywords.pl
keywords.pl.all
keywords.pt
keywords.pt.all
keywords.ro
keywords.ro.all
keywords.ru
keywords.ru.all
keywords.sk
keywords.sk.all
keywords.sl
keywords.sl.all
keywords.so
keywords.so.all
keywords.sq
keywords.sq.all
keywords.sr
keywords.sr.all
keywords.sv
keywords.sv.all
keywords.sw
keywords.sw.all
keywords.ta
keywords.ta.all
keywords.te
keywords.te.all
keywords.th
keywords.th.all
keywords.tl
keywords.tl.all
keywords.tr
keywords.tr.all
keywords.uk
keywords.uk.all
keywords.unknown
keywords.unknown.all
keywords.uri
keywords.uri.all
keywords.vi
keywords.vi.all
keywords.zxx
keywords.zxx.all
keywords_all
keywords_all.all
label
label.VRT
label.VRT.all
label.af
label.af.all
label.an
label.an.all
label.ar
label.ar.all
label.ast
label.ast.all
label.be
label.be.all
label.bg
label.bg.all
label.br
label.br.all
label.ca
label.ca.all
label.cs
label.cs.all
label.cy
label.cy.all
label.da
label.da.all
label.de
label.de.all
label.def
label.def.all
label.default
label.default.all
label.el
label.el.all
label.en
label.en.all
label.es
label.es.all
label.et
label.et.all
label.eu
label.eu.all
label.fi
label.fi.all
label.fr
label.fr.all
label.gaa
label.gaa.all
label.gl
label.gl.all
label.he
label.he.all
label.hr
label.hr.all
label.ht
label.ht.all
label.hu
label.hu.all
label.id
label.id.all
label.is
label.is.all
label.it
label.it.all
label.ja
label.ja.all
label.la
label.la.all
label.lt
label.lt.all
label.lv
label.lv.all
label.mk
label.mk.all
label.ms
label.ms.all
label.mt
label.mt.all
label.nb
label.nb.all
label.nl
label.nl.all
label.no
label.no.all
label.oc
label.oc.all
label.pl
label.pl.all
label.pt
label.pt.all
label.ro
label.ro.all
label.ru
label.ru.all
label.sk
label.sk.all
label.sl
label.sl.all
label.so
label.so.all
label.sq
label.sq.all
label.sr
label.sr.all
label.sv
label.sv.all
label.sw
label.sw.all
label.tl
label.tl.all
label.tr
label.tr.all
label.uk
label.uk.all
label.unknown
label.unknown.all
label.yi
label.yi.all
label.zxx
label.zxx.all
label_all
label_all.all
media
media.height
media.originalRights
media.originalRights.cy
media.originalRights.cy.all
media.originalRights.de
media.originalRights.de.all
media.originalRights.default
media.originalRights.default.all
media.originalRights.en
media.originalRights.en.all
media.originalRights.fr
media.originalRights.fr.all
media.originalRights.unknown
media.originalRights.unknown.all
media.originalRights.uri
media.originalRights.uri.all
media.type
media.type.all
media.url
media.url.all
media.width
media.withRights
media.withRights.all
metadataRights
metadataRights.uri
metadataRights.uri.all
provider
provider.all
resourceType
resourceType.all

*
*/
