include "application.conf"

application.secret="tkt/@CDv7yLbP9TJndXf]e8U3yWKCmQeKR2k/_YknAUd5piMW^D2QEgsm?I2DiYB"

mongo {
	host: "leffe.image.ece.ntua.gr"
	port: 27017
	dbname: "with-prod-newspaces"
}

elasticsearch {
	enable: false 
	host: "leffe.image.ece.ntua.gr"
	port: 19300
	cluster: "elastic2leffe"
	index.name: "with-prod-maria-27092016"
	index.mapping.resource: "resource.mapping"
	index.mapping.annotation: "annotation.mapping"
	old_index.name: ""
	index.num_of_shards: 5
	index.num_of_replicas: 0
	alias.name: ""
	searchWithin.fields="label_all^4,description_all^2,keywords_all,altLabels_all"
}